services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - nextcloud-config-volume:/config
      - nextcloud-data-volume:/data
    ports:
      - 9003:443
    restart: unless-stopped
    
volumes:
  nextcloud-config-volume:
    driver: local
    driver_opts:
      type: none
      device: /data/homelab/docker/volumes/nextcloud/config
      o: bind
  nextcloud-data-volume:
    driver: local
    driver_opts:
      type: none
      device: /data/homelab/docker/volumes/nextcloud/data
      o: bind

    